### PR TITLE
Fixed freebsd compilation error relating to recent multilevel sensor

### PR DESCRIPTION
**Pull request by ryanwinter**
Matching the code in the openzwave base repo.

### CODE REVIEW

**Comment by robbiet480** [comment]
@pvizeli Based on reading https://github.com/home-assistant/home-assistant/issues/22697, Zwave install is broken entirely for those on macOS and FreeBSD. This PR needs to get merged and HA itself needs to bump ozw dep to latest, then probably get it into a 0.91.1 or .2. Can you get this merged? I would but I have no context on the matter.

**Comment by robbiet480** [comment]
Fixes breakage introduced by #2
